### ISSUE TITLE
Need Google cloud function notification feature not working

### ISSUE THREAD

**Issue by tusharhatwar1997** [ganainy/Our_chat#5]

**Comment by ganainy** [comment]
Sorry for late response 

// Create and Deploy Your First Cloud Functions
// https://firebase.google.com/docs/functions/write-firebase-functions
//https://firebase.google.com/docs/cloud-messaging/send-message
 
Here is the index.js file
https://drive.google.com/file/d/1JjE9c0WsU3OMTq_EbyK2XMtR27qIDKIm/view?usp=sharing

**Comment by tusharhatwar1997** [comment]
Thank you
